### ISSUE TITLE
dockerfs

### ISSUE THREAD

**Issue by evanrich** [nlopez/k8s_home#1]
Are you just mounting your local storage "dockerfs" over nfs?  or is it a local mount on your node?

Awesome repo!  I'm new to K8s, trying to learn following your configs here, if yo u have some time would it be possible for you to write some more detailed info about some of your settings?

Thanks!

**Comment by nlopez** [comment]
Hey @evanrich ! `/dockerfs` is a local mount on my k8s nodes and all my nfs mounts are done via k8s `PerstentVolume` and `PersistentVolumeClaim` objects [here](https://github.com/nlopez/k8s_home/tree/master/nfs)
