### ISSUE TITLE
does your prometheus folder deploy a fully functional prometheus ?

### ISSUE THREAD

**Issue by evanrich** [nlopez/k8s_home#12]
quick question, does your prometheus operator deployment deploy a fully working prometheus instance that picks up "servicemonitors" automatically?  new to prometheus-operator, wondering if i can use this in place of my current config.

Thanks!

**Comment by nlopez** [comment]
Hey @evanrich ! Yes it does pick up ServiceMonitors automatically.  [This bit](https://github.com/nlopez/k8s_home/blob/fa84d4377f161f92a8dc5b5ea404289131a44c2f/mon/prometheus/netdata-external.yaml#L162-L165) of config makes the Prom operator look for SMs in all namespaces, and [here](https://github.com/nlopez/k8s_home/blob/fa84d4377f161f92a8dc5b5ea404289131a44c2f/media/tautulli/servicemonitor.yaml#L1) is a sample SM in another namespace (media).
